name: LoginSpawn
version: 1.0
author: ipodtouch0218

main: me.ipodtouch0218.loginspawn.LoginSpawnMain
commands:
  spawn:
    usage: /<command>
    description: Teleports you to the spawn of the world.
    permission: loginspawn.command.spawn
  setspawn:
    usage: /<command>
    description: Sets the spawn to where you are standing.
    permission: loginspawn.command.setspawn